## this workflow for Develop, master- 
name: CI
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: cache node_modules
        uses:  actions/cache@v1
        with:
          Path: `/.npm  (different in windows)
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json')}} 
          restore-keys: |
            ${{ runner.os}}-node-
      - uses:  Use NodJS
      - uses:  actions/setup-node@v1
        with:
          node-version:  "12.x"
      - run: npm ci 
      - run: npm run format:check
      - run: npm test  -- --coverage
        env:
          CI: true
      - name: Upload Test --coverage  
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: code-coverage    
      - name: Build Project
        if: gitbhub.event_name == 'push'
        run: npm run build 
        - name: Upload Build Folder
          if: gitbhub.event_name == 'push'  
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build 
      - name:  ZIP Assets
            if: gitbhub.event_name == 'push' && github.ref == 'refs/heads/master'
            run: |
              zip -r build.zip ./build
              zip -r coverage.zip ./coverage
      - name:  Create a Release
        if: gitbhub.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${ secrets.GITHUB_TOKEN }
      - name: Deploy to Staging
        if: gitbhub.event_name == 'push' 
        run:  npx surge
        


